# Generated by Django 6.0.5 on 2026-05-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_create_admin_user'),
    ]

    operations = [
    ]
